title: The BAD Dataset
#logo: /assets/img/logo.png
description: The Bystander Affect Detection Dataset for Failure Detection in HRI.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
