title: Minimal theme
logo: https://far-lab.github.io/bad-dataset/assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
relative_url: https://far-lab.github.io/bad-dataset/
